config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users
  root "pages#home"
  get "productos", to: "pages#home_products"
  # get "registrarse", to ""
  resources :users

  resource :shopping_cart, only: [:show]

  post 'shopping_cart/add/:product_id', to: "shopping_cart#add"
  match 'shopping_cart/remove/:product_id', to: "shopping_cart#remove", via: [:post]
  match 'shopping_cart/zap', to: "shopping_cart#zap", via: [:post, :get]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :orders
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<br>
<div class="container" style="background-color: white; padding-left: 10%; padding-right: 2%; height: 630px;">
  <br>
  <h3>Tu perfil</h3>
  <br>
  <span style=" float: left; width: 50%">
    <%= render @user %>
    <%= fields_for @user do |form| %>
        <div>
          <br>
          <font size="+1"  style="font-weight: 500">Nombre</font>
          <%= form.text_field :name, class: "form-control",:disabled => true, style: "border-color: #FC83E2; border-width: 2px" %>
          <br>
          <font size="+1"  style="font-weight: 500">Apellido</font>
          <%= form.text_field :last_name, class: "form-control",:disabled => true, style: "border-color: #FC83E2; border-width: 2px" %>
          <br>
          <font size="+1"  style="font-weight: 500">Email</font>
          <%= form.email_field :email, class: "form-control",:disabled => true, style: "border-color: #FC83E2; border-width: 2px" %>
          <br>
          <font size="+1"  style="font-weight: 500">Contraseña</font>
          <%= form.password_field :password,value: "123456", class: "form-control",:disabled => true, style: "border-color: #FC83E2; border-width: 2px" %>
          <br>
          <font size="+1"  style="font-weight: 500">Numero Telefonico</font>
          <%= form.text_field :phone, class: "form-control",:disabled => true, style: "border-color: #FC83E2; border-width: 2px" %>
          <br>
          <%= link_to "Editar Informacion", edit_user_registration_path, class: "btn btn-primary",  style: "background-color: #FC83E2; border-color: #FC83E2" %>
        </div>
    <% end %>
  </span>
  <span style=" float:right; padding-right: 5%; padding-top: 5%">
    <%(1..17).each do |n| %>
    <br>
      <%end %>
    <div style=" float:right">
    <%= image_tag("transbank.png", width: "280dp", height: "150dp", background: "#FFFFFF") %>
    </div>
  </span>
  <br>
</div>